name: "synthetic"
num_epochs: 100000
learning_rate: 0.001
weight_decay: 0
batch_size: 256
gradient_clipping: False
early_stopping: True

support_size: 5
query_size: 27

hidden_representation_size: 32
n_hidden_layers: 3
hidden_size: 32
dropout_rate: 0.1
is_classifier: False

train_data_path: data/01_synthetic/train
val_data_path: data/01_synthetic/val
test_data_path: data/01_synthetic/test