name: "openml_clf"
num_epochs: 100000
learning_rate: 0.001
weight_decay: 0
batch_size: 37
gradient_clipping: False
early_stopping: True

support_size: 3
query_size: 29

hidden_representation_size: 32
n_hidden_layers: 3
hidden_size: 32
dropout_rate: 0.1
is_classifier: True

train_data_path: data/03_openml_clf/train
val_data_path: data/03_openml_clf/val
test_data_path: data/03_openml_clf/test