name: "new_classes"
classification: true
num_epochs: 5
learning_rate: 0.001
weight_decay: 0.0001
batch_size: 256
gradient_clipping: True

support_size: 5
query_size: 27

hidden_representation_size: 16
n_hidden_layers: 1
hidden_size: 16
dropout_rate: 0.1

train_data_path: data/05_big_data/train
val_data_path: data/05_big_data/val
test_data_path: data/05_big_data/test