name: "openml"
num_epochs: 100000
learning_rate: 0.001
weight_decay: 0.0001
batch_size: 256
gradient_clipping: True

support_size: 5
query_size: 27

hidden_representation_size: 32
n_hidden_layers: 3
hidden_size: 32
dropout_rate: 0.1

train_data_path: data/02_openml/train
val_data_path: data/02_openml/val
test_data_path: data/02_openml/test