num_epochs: 100000
learning_rate: 0.0001
weight_decay: 0.0001
batch_size: 32
gradient_clipping: True

support_size: 5
query_size: 27

hidden_representation_size: 32
n_hidden_layers: 3
hidden_size: 32
dropout_rate: 0.1