name: "synthetic_small"
num_epochs: 20
learning_rate: 0.001
weight_decay: 0.0001
batch_size: 32
gradient_clipping: True

support_size: 5
query_size: 10

hidden_representation_size: 4
n_hidden_layers: 2
hidden_size: 8
dropout_rate: 0.1

train_data_path: data/06_synthetic_small/train
val_data_path: data/06_synthetic_small/val
test_data_path: data/06_synthetic_small/test